import type {Metadata} from "next";
import "../globals.css";
import React from "react";
import StoreProvider from "@/store/StoreProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
        params
    }: Readonly<{
        children: React.ReactNode,
        params: Promise<{ lang: string }>
    }>
) {

    const {lang} = await params

    return (
        <html lang={lang}>
        <body>
        <StoreProvider>
            {children}
        </StoreProvider>
        </body>
        </html>
    );
}
